name: Deploy

env:
    REPOSITORY: ${{github.repository}}
    OWNER: ${{github.actor}}

on:
  workflow_run:
    workflows: ["Docker"]
    branches:
      - main
      - next
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        CONTAINER_NAME: ${basename `git rev-parse --show-toplevel`}
    steps:
      - name: Get container name
        run: |
          echo "container name: $CONTAINER_NAME"
          echo "repository: $REPOSITORY"
          echo "owner: $OWNER"
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1.2.0
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          HOST: op://end.works/end.works/URL
          PORT: op://end.works/end.works/port
          USERNAME: op://end.works/end.works/username
          KEY: op://end.works/SSH Key/private key
          FINGERPRINT: op://end.works/SSH Key/fingerprint

      - name: Deploy image to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.HOST }}
          port: ${{ env.PORT }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          fingerprint: ${{ env.FINGERPRINT }}
          script: |
            docker pull ghcr.io/${{ github.repository }}:next
            docker stop ${{ env.CONTAINER_NAME }}
            docker rm ${{ env.CONTAINER_NAME }}
            docker run -p 8084:3000/tcp -ti -d --restart unless-stopped --name ${{ env.CONTAINER_NAME }} ghcr.io/${{ github.repository }}:next
