name: Deploy

on:
  workflow_run:
    workflows: ["Docker"]
    branches:
      - main
      - next
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set container name
        id: set-name
        run: |
          echo "repo=${{github.repository}}" >> "$GITHUB_ENV"
          echo "owner=${{github.repository_owner}}" >> "$GITHUB_ENV"
          echo "container_name=${${{github.repository}}#${{github.repository_owner}}}"

      - name: Get container name
        id: get-name
        run: |
          echo "container_name: ${{ env.container_name }}"
          echo "repo: ${{ env.repo }}"
          echo "owner: ${{ env.owner }}"

      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1.2.0
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          HOST: op://end.works/end.works/URL
          PORT: op://end.works/end.works/port
          USERNAME: op://end.works/end.works/username
          KEY: op://end.works/SSH Key/private key
          FINGERPRINT: op://end.works/SSH Key/fingerprint

      - name: Generate job summary
        run: |
          echo "### Deploying to server! :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- host: ${{env.HOST}}" >> $GITHUB_STEP_SUMMARY
          echo "- port: ${{env.POST}}" >> $GITHUB_STEP_SUMMARY
          echo "- username: ${{env.USERNAME}}" >> $GITHUB_STEP_SUMMARY

      - name: Deploy image to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.HOST }}
          port: ${{ env.PORT }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          fingerprint: ${{ env.FINGERPRINT }}
          script: |
            docker pull ghcr.io/${{ github.repository }}:next
            docker stop ${{ env.container_name }}
            docker rm ${{ env.container_name }}
            docker run -p 8084:3000/tcp -ti -d --restart unless-stopped --name ${{ env.container_name }} ghcr.io/${{ github.repository }}:next
